# .pre-commit-config.yml

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3


  - repo: local
    hooks:
      - id: remove-empty-files
        name: Remove Empty Files
        entry: bash -c 'find . -type f -empty -delete'
        language: system
        files: *
